# Generated by Django 2.2.12 on 2020-06-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_customtext_r4'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='r5',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
