# Generated by Django 2.2.12 on 2020-06-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_customtext_r5'),
    ]

    operations = [
        migrations.CreateModel(
            name='R1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r1', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='R2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r2', models.BigIntegerField()),
            ],
        ),
    ]
