# Generated by Django 2.2.12 on 2020-06-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_r1_r2'),
    ]

    operations = [
        migrations.CreateModel(
            name='R3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r3', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='R4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r4', models.BigIntegerField()),
            ],
        ),
    ]
