# Generated by Django 2.2.12 on 2020-06-03 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0010_r1_r2"),
    ]

    operations = [
        migrations.AddField(
            model_name="r1",
            name="r3",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="r1_r3",
                to="home.CustomText",
            ),
        ),
        migrations.AddField(
            model_name="r2",
            name="r1",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="r2_r1",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
