# Generated by Django 2.2.12 on 2020-06-03 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_r67_rt'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='r2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homepage_r2', to='home.Test'),
        ),
        migrations.AddField(
            model_name='r4',
            name='r2',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='r4',
            name='r3',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r4_r3', to='home.R67'),
        ),
    ]
